module.exports = {
  appKey: 'vtexappkey-pocsanbesfera-SOQXZG',
  appToken:
    'ZLVUDPKBHTINMMTVCJRLMSWMHQDQQIKOUPBPWXNIOAHMDAKGHQLVFWXVLXDPFGTAATJCORXVUISFLZIHQZNDRMKXCHCIJQYWBLTFHTGDOPQJMSZLVIHOAZGJKJDNWRBN',
}
